[program:fba_celery_flower]
directory=/fba/backend
command=/usr/local/bin/python -m app.task.flower --address=0.0.0.0 --port=8555 --url-prefix=flower
user=root
autostart=true
autorestart=true
startretries=5
redirect_stderr=true
stdout_logfile=/var/log/fba/fba_celery_flower.log
stdout_logfile_maxbytes=5MB
stdout_logfile_backups=5
