[program:fba_celery_worker]
directory=/fba/backend
command=/usr/local/bin/celery -A app.task.celery:celery_app worker -c 4 --loglevel=INFO --hostname=fba@%%h
user=root
autostart=true
autorestart=true
startretries=5
redirect_stderr=true
stdout_logfile=/var/log/fba/fba_celery_worker.log
stdout_logfile_maxbytes=5MB
stdout_logfile_backups=5
