from typing import Any

class AsyncIOPool:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

def build_async_tracer(*args: Any, **kwargs: Any) -> Any: ...
def patch_celery_tracer() -> bool: ...
