from typing import Any

class WeChatPayType:
    NATIVE: Any

class WeChatPay:
    _core: Any
    def __init__(self, **kwargs: Any) -> None: ...
    def pay(self, **kwargs: Any) -> tuple[int, str | dict[str, Any]]: ...
    def query(self, **kwargs: Any) -> tuple[int, str | dict[str, Any]]: ...
    def close(self, **kwargs: Any) -> tuple[int, Any]: ...
    def refund(self, **kwargs: Any) -> tuple[int, str | dict[str, Any]]: ...
    def callback(self, **kwargs: Any) -> str | dict[str, Any] | None: ...
