from typing import Any

class AliPay:
    _ordered_data: Any
    def __init__(self, **kwargs: Any) -> None: ...
    def api_alipay_trade_page_pay(self, **kwargs: Any) -> str: ...
    def api_alipay_trade_query(self, **kwargs: Any) -> dict[str, Any]: ...
    def api_alipay_trade_close(self, **kwargs: Any) -> dict[str, Any]: ...
    def api_alipay_trade_refund(self, **kwargs: Any) -> dict[str, Any]: ...
    def verify(self, data: dict[str, Any], signature: str) -> bool: ...

class DCAliPay(AliPay): ...
