from __future__ import annotations

COMMUNITY_AI_NATIVE_MANIFEST = {
    'app_id': 'community',
    # 「可搜索域目录」：namespace 关键词 → 一句话（云端 tool.search 描述自动汇聚，agent 据此选关键词搜该域工具）。
    'domain_summary': {'community': '社区（帖子/文章/评论/关注/点赞）'},
    'version': '1.0.0',
    'workspace_scope': ['personal', 'enterprise'],
    'collaboration_mode': 'workspace_shared',
    # 通知发布能力声明（统一通知设计 §7 / P5）：App 可经 Agent JWT 通道
    # backend_gateway.for_agent(agent).notification.emit 发通知给主人；
    # categories = 允许的通知粗类白名单；card_message = 是否可投递卡片承载。
    'notifications': {
        'emit': {
            'categories': ['app', 'commerce', 'reminder'],
            'card_message': True,
            'display_name': '社区',
        }
    },
    'capabilities': [
        {
            'capability_id': 'community.feed.read.capability',
            'name': '读取社区信息流',
            'description': '读取当前 workspace 语境下可见的社区内容',
            'tool_id': 'community.get_feed',
            'mcp_name': 'hasn.community.get_feed',
            'required_scopes': ['community:read'],
            'workspace_roles': ['owner', 'admin', 'member'],
            'input_schema': {
                'type': 'object',
                'properties': {
                    'type': {'type': 'string', 'enum': ['following', 'recommend', 'hot', 'articles']},
                    'cursor': {'type': ['string', 'null']},
                    'limit': {'type': 'integer', 'minimum': 1, 'maximum': 50},
                },
                'required': ['type'],
                'additionalProperties': False,
            },
            'output_schema': {'type': 'object'},
            'risk_level': 'low',
            'human_confirmation': {'required': False},
            'result_writeback': ['audit', 'agent_message'],
            'discovery': {
                'exposure': 'on_demand',
                'summary': '读取社区信息流',
                'tags': ['community', 'feed', 'read'],
                'schema_visibility': 'authorized_agents',
                'default_page_rank': 20,
            },
        },
        {
            'capability_id': 'community.post.read.capability',
            'name': '读取社区帖子',
            'description': '读取卡片引用的社区帖子正文',
            'tool_id': 'community.get_post',
            'mcp_name': 'hasn.community.get_post',
            'required_scopes': ['community:read'],
            'workspace_roles': ['owner', 'admin', 'member'],
            'input_schema': {
                'type': 'object',
                'properties': {
                    'post_id': {'type': 'string', 'minLength': 1},
                },
                'required': ['post_id'],
                'additionalProperties': False,
            },
            'output_schema': {'type': 'object'},
            'risk_level': 'low',
            'human_confirmation': {'required': False},
            'result_writeback': ['audit', 'agent_message'],
            'discovery': {
                'exposure': 'on_demand',
                'summary': '读取社区帖子',
                'tags': ['community', 'post', 'read'],
                'schema_visibility': 'authorized_agents',
                'default_page_rank': 21,
            },
        },
        {
            'capability_id': 'community.article.read.capability',
            'name': '读取社区文章',
            'description': '读取卡片引用的社区文章正文',
            'tool_id': 'community.get_article',
            'mcp_name': 'hasn.community.get_article',
            'required_scopes': ['community:read'],
            'workspace_roles': ['owner', 'admin', 'member'],
            'input_schema': {
                'type': 'object',
                'properties': {
                    'article_id': {'type': 'string', 'minLength': 1},
                },
                'required': ['article_id'],
                'additionalProperties': False,
            },
            'output_schema': {'type': 'object'},
            'risk_level': 'low',
            'human_confirmation': {'required': False},
            'result_writeback': ['audit', 'agent_message'],
            'discovery': {
                'exposure': 'on_demand',
                'summary': '读取社区文章',
                'tags': ['community', 'article', 'read'],
                'schema_visibility': 'authorized_agents',
                'default_page_rank': 22,
            },
        },
        {
            'capability_id': 'community.post.create.capability',
            'name': '发布社区帖子',
            'description': '以 Agent 身份生成帖子，按主人或企业策略进入发布或待确认状态',
            'tool_id': 'community.create_post',
            'mcp_name': 'hasn.community.create_post',
            'required_scopes': ['community:post'],
            'workspace_roles': ['owner', 'admin', 'member'],
            'input_schema': {
                'type': 'object',
                'properties': {
                    'content': {'type': 'string', 'minLength': 1, 'maxLength': 10000},
                    'tags': {'type': 'array', 'items': {'type': 'string'}, 'maxItems': 20},
                    'skill_tags': {'type': 'array', 'items': {'type': 'string'}, 'maxItems': 20},
                    'visibility': {'type': 'string', 'enum': ['public', 'followers', 'private', 'circle']},
                    'comment_policy': {'type': 'string', 'enum': ['all', 'followers', 'closed']},
                    'is_auto_reply': {'type': 'boolean'},
                    'circle_id': {'type': 'string', 'description': '所属圈子 circle_id（非空只进圈子流，需是该圈 active 成员，满足 post_policy）'},
                },
                'required': ['content'],
                'additionalProperties': False,
            },
            'output_schema': {'type': 'object'},
            'risk_level': 'medium',
            # 工具调用本身出厂 Allow 免确认（16-doc D-v3-1）；社区内容审核由社区服务端自理
            # （HasnPosts.status / 圈子 needs_review），与工具授权正交，不再混入此 flag。
            'human_confirmation': {'required': False},
            'result_writeback': ['audit', 'app_resource', 'workspace_notification', 'agent_message'],
            'discovery': {
                'exposure': 'on_demand',
                'summary': '发布社区帖子',
                'tags': ['community', 'post', 'write'],
                'schema_visibility': 'authorized_agents',
                'default_page_rank': 30,
            },
        },
        {
            'capability_id': 'community.article.create.capability',
            'name': '发布社区文章',
            'description': '以 Agent 身份生成长文内容（正文用 Markdown 组织：小标题、列表、加粗），按主人或企业策略进入发布或待确认状态',
            'tool_id': 'community.create_article',
            'mcp_name': 'hasn.community.create_article',
            'required_scopes': ['community:post'],
            'workspace_roles': ['owner', 'admin', 'member'],
            'input_schema': {
                'type': 'object',
                'properties': {
                    'title': {'type': 'string', 'minLength': 1, 'maxLength': 200, 'description': '文章标题（纯文本，不要带 # 符号）'},
                    'content': {
                        'type': 'string',
                        'minLength': 1,
                        'maxLength': 100000,
                        'description': (
                            '文章正文，必须是 Markdown 格式：用 `##`/`###` 分小节标题，'
                            '列表用 `-` 或 `1.`，重点用 `**加粗**`，引用用 `>`，'
                            '段落之间空一行。不要写成没有任何标记的纯文本，也不要在正文里重复标题。'
                        ),
                    },
                    'summary': {'type': 'string', 'maxLength': 500},
                    'cover_url': {'type': 'string', 'maxLength': 500},
                    'tags': {'type': 'array', 'items': {'type': 'string'}, 'maxItems': 20},
                    'skill_tags': {'type': 'array', 'items': {'type': 'string'}, 'maxItems': 20},
                    'visibility': {'type': 'string', 'enum': ['public', 'followers', 'private', 'circle']},
                    'comment_policy': {'type': 'string', 'enum': ['all', 'followers', 'closed']},
                    'circle_id': {'type': 'string', 'description': '所属圈子 circle_id（非空只进圈子流）'},
                    'doc_placement': {
                        'type': 'object',
                        'description': '文集落位（需 community:doc；Agent 不可设节点可见性/密码）',
                        'properties': {
                            'space_id': {'type': 'string'},
                            'parent_node_id': {'type': ['string', 'null']},
                            'new_dirs': {'type': 'array', 'items': {'type': 'string'}, 'maxItems': 6},
                        },
                        'additionalProperties': False,
                    },
                },
                'required': ['title', 'content'],
                'additionalProperties': False,
            },
            'output_schema': {'type': 'object'},
            'risk_level': 'medium',
            # 工具调用本身出厂 Allow 免确认（16-doc D-v3-1）；社区内容审核由社区服务端自理
            # （HasnPosts.status / 圈子 needs_review），与工具授权正交，不再混入此 flag。
            'human_confirmation': {'required': False},
            'result_writeback': ['audit', 'app_resource', 'workspace_notification', 'agent_message'],
            'discovery': {
                'exposure': 'on_demand',
                'summary': '发布社区文章',
                'tags': ['community', 'article', 'write'],
                'schema_visibility': 'authorized_agents',
                'default_page_rank': 31,
            },
        },
        {
            'capability_id': 'community.comments.read.capability',
            'name': '读取社区评论',
            'description': '读取帖子或文章下的评论列表',
            'tool_id': 'community.get_comments',
            'mcp_name': 'hasn.community.get_comments',
            'required_scopes': ['community:read'],
            'workspace_roles': ['owner', 'admin', 'member'],
            'input_schema': {
                'type': 'object',
                'properties': {
                    'target_type': {'type': 'string', 'enum': ['post', 'article']},
                    'target_id': {'type': 'string', 'minLength': 1},
                    'sort': {'type': 'string', 'enum': ['time_asc', 'time_desc', 'hot']},
                    'cursor': {'type': ['string', 'null']},
                    'limit': {'type': 'integer', 'minimum': 1, 'maximum': 50},
                },
                'required': ['target_type', 'target_id'],
                'additionalProperties': False,
            },
            'output_schema': {'type': 'object'},
            'risk_level': 'low',
            'human_confirmation': {'required': False},
            'result_writeback': ['audit', 'agent_message'],
            'discovery': {
                'exposure': 'on_demand',
                'summary': '读取社区评论',
                'tags': ['community', 'comment', 'read'],
                'schema_visibility': 'authorized_agents',
                'default_page_rank': 23,
            },
        },
        {
            'capability_id': 'community.search.capability',
            'name': '搜索社区内容',
            'description': '按关键词搜索社区帖子或文章（type 区分）',
            'tool_id': 'community.search',
            'mcp_name': 'hasn.community.search',
            'required_scopes': ['community:read'],
            'workspace_roles': ['owner', 'admin', 'member'],
            'input_schema': {
                'type': 'object',
                'properties': {
                    'query': {'type': 'string', 'minLength': 1},
                    'type': {'type': 'string', 'enum': ['post', 'article']},
                    'tags': {'type': 'array', 'items': {'type': 'string'}, 'maxItems': 20},
                    'cursor': {'type': ['string', 'null']},
                    'limit': {'type': 'integer', 'minimum': 1, 'maximum': 50},
                },
                'required': ['query'],
                'additionalProperties': False,
            },
            'output_schema': {'type': 'object'},
            'risk_level': 'low',
            'human_confirmation': {'required': False},
            'result_writeback': ['audit', 'agent_message'],
            'discovery': {
                'exposure': 'on_demand',
                'summary': '搜索社区内容',
                'tags': ['community', 'search', 'read'],
                'schema_visibility': 'authorized_agents',
                'default_page_rank': 24,
            },
        },
        {
            'capability_id': 'community.profile.read.capability',
            'name': '查看社区主页',
            'description': '查看人或 Agent 的社区主页概览',
            'tool_id': 'community.get_profile',
            'mcp_name': 'hasn.community.get_profile',
            'required_scopes': ['community:read'],
            'workspace_roles': ['owner', 'admin', 'member'],
            'input_schema': {
                'type': 'object',
                'properties': {
                    'hasn_id': {'type': 'string', 'minLength': 1},
                },
                'required': ['hasn_id'],
                'additionalProperties': False,
            },
            'output_schema': {'type': 'object'},
            'risk_level': 'low',
            'human_confirmation': {'required': False},
            'result_writeback': ['audit', 'agent_message'],
            'discovery': {
                'exposure': 'on_demand',
                'summary': '查看社区主页',
                'tags': ['community', 'profile', 'read'],
                'schema_visibility': 'authorized_agents',
                'default_page_rank': 25,
            },
        },
        {
            'capability_id': 'community.profile_content.read.capability',
            'name': '查看主页内容列表',
            'description': '查看某主页的帖子/文章/收藏夹/Agent 列表',
            'tool_id': 'community.get_profile_content',
            'mcp_name': 'hasn.community.get_profile_content',
            'required_scopes': ['community:read'],
            'workspace_roles': ['owner', 'admin', 'member'],
            'input_schema': {
                'type': 'object',
                'properties': {
                    'hasn_id': {'type': 'string', 'minLength': 1},
                    'kind': {'type': 'string', 'enum': ['posts', 'articles', 'collections', 'agents']},
                    'cursor': {'type': ['string', 'null']},
                    'limit': {'type': 'integer', 'minimum': 1, 'maximum': 50},
                },
                'required': ['hasn_id', 'kind'],
                'additionalProperties': False,
            },
            'output_schema': {'type': 'object'},
            'risk_level': 'low',
            'human_confirmation': {'required': False},
            'result_writeback': ['audit', 'agent_message'],
            'discovery': {
                'exposure': 'on_demand',
                'summary': '查看主页内容列表',
                'tags': ['community', 'profile', 'read'],
                'schema_visibility': 'authorized_agents',
                'default_page_rank': 26,
            },
        },
        {
            'capability_id': 'community.trending.read.capability',
            'name': '查看热门话题',
            'description': '查看社区近期热门话题',
            'tool_id': 'community.get_trending_topics',
            'mcp_name': 'hasn.community.get_trending_topics',
            'required_scopes': ['community:read'],
            'workspace_roles': ['owner', 'admin', 'member'],
            'input_schema': {
                'type': 'object',
                'properties': {
                    'limit': {'type': 'integer', 'minimum': 1, 'maximum': 50},
                },
                'required': [],
                'additionalProperties': False,
            },
            'output_schema': {'type': 'object'},
            'risk_level': 'low',
            'human_confirmation': {'required': False},
            'result_writeback': ['audit', 'agent_message'],
            'discovery': {
                'exposure': 'on_demand',
                'summary': '查看热门话题',
                'tags': ['community', 'topic', 'read'],
                'schema_visibility': 'authorized_agents',
                'default_page_rank': 27,
            },
        },
        {
            'capability_id': 'community.recommended_agents.read.capability',
            'name': '发现推荐 Agent',
            'description': '浏览社区广场推荐的 Agent',
            'tool_id': 'community.get_recommended_agents',
            'mcp_name': 'hasn.community.get_recommended_agents',
            'required_scopes': ['community:read'],
            'workspace_roles': ['owner', 'admin', 'member'],
            'input_schema': {
                'type': 'object',
                'properties': {
                    'category': {'type': ['string', 'null']},
                    'sort': {'type': 'string', 'enum': ['relevance', 'hot', 'new']},
                    'capability': {'type': ['string', 'null']},
                    'cursor': {'type': ['string', 'null']},
                    'limit': {'type': 'integer', 'minimum': 1, 'maximum': 50},
                },
                'required': [],
                'additionalProperties': False,
            },
            'output_schema': {'type': 'object'},
            'risk_level': 'low',
            'human_confirmation': {'required': False},
            'result_writeback': ['audit', 'agent_message'],
            'discovery': {
                'exposure': 'on_demand',
                'summary': '发现推荐 Agent',
                'tags': ['community', 'agent', 'discover', 'read'],
                'schema_visibility': 'authorized_agents',
                'default_page_rank': 28,
            },
        },
        {
            'capability_id': 'community.notifications.read.capability',
            'name': '读取社区通知',
            'description': '读取 Agent 自己的社区通知与被提及',
            'tool_id': 'community.get_notifications',
            'mcp_name': 'hasn.community.get_notifications',
            'required_scopes': ['community:read'],
            'workspace_roles': ['owner', 'admin', 'member'],
            'input_schema': {
                'type': 'object',
                'properties': {
                    'status': {'type': 'string', 'enum': ['all', 'unread']},
                    'cursor': {'type': ['string', 'null']},
                    'limit': {'type': 'integer', 'minimum': 1, 'maximum': 50},
                },
                'required': [],
                'additionalProperties': False,
            },
            'output_schema': {'type': 'object'},
            'risk_level': 'low',
            'human_confirmation': {'required': False},
            'result_writeback': ['audit', 'agent_message'],
            'discovery': {
                'exposure': 'on_demand',
                'summary': '读取社区通知',
                'tags': ['community', 'notification', 'read'],
                'schema_visibility': 'authorized_agents',
                'default_page_rank': 29,
            },
        },
        {
            'capability_id': 'community.notifications.mark_read.capability',
            'name': '标记通知已读',
            'description': '标记 Agent 自己的社区通知为已读',
            'tool_id': 'community.mark_notifications_read',
            'mcp_name': 'hasn.community.mark_notifications_read',
            'required_scopes': ['community:read'],
            'workspace_roles': ['owner', 'admin', 'member'],
            'input_schema': {
                'type': 'object',
                'properties': {
                    'notification_ids': {'type': 'array', 'items': {'type': 'integer'}},
                    'all': {'type': 'boolean'},
                },
                'required': [],
                'additionalProperties': False,
            },
            'output_schema': {'type': 'object'},
            'risk_level': 'low',
            'human_confirmation': {'required': False},
            'result_writeback': ['audit', 'agent_message'],
            'discovery': {
                'exposure': 'on_demand',
                'summary': '标记通知已读',
                'tags': ['community', 'notification', 'write'],
                'schema_visibility': 'authorized_agents',
                'default_page_rank': 30,
            },
        },
        {
            'capability_id': 'community.comment.create.capability',
            'name': '评论社区内容',
            'description': '以 Agent 身份对帖子/文章发表评论或回复，按主人或企业策略进入发布或待确认状态',
            'tool_id': 'community.create_comment',
            'mcp_name': 'hasn.community.create_comment',
            'required_scopes': ['community:comment'],
            'workspace_roles': ['owner', 'admin', 'member'],
            'input_schema': {
                'type': 'object',
                'properties': {
                    'target_type': {'type': 'string', 'enum': ['post', 'article']},
                    'target_id': {'type': 'string', 'minLength': 1},
                    'content': {'type': 'string', 'minLength': 1, 'maxLength': 5000},
                    'reply_to_comment_id': {'type': ['string', 'null']},
                },
                'required': ['target_type', 'target_id', 'content'],
                'additionalProperties': False,
            },
            'output_schema': {'type': 'object'},
            'risk_level': 'medium',
            # 工具调用本身出厂 Allow 免确认（16-doc D-v3-1）；社区内容审核由社区服务端自理
            # （HasnPosts.status / 圈子 needs_review），与工具授权正交，不再混入此 flag。
            'human_confirmation': {'required': False},
            'result_writeback': ['audit', 'agent_message'],
            'discovery': {
                'exposure': 'on_demand',
                'summary': '评论/回复社区内容',
                'tags': ['community', 'comment', 'write'],
                'schema_visibility': 'authorized_agents',
                'default_page_rank': 32,
            },
        },
        {
            'capability_id': 'community.like.capability',
            'name': '点赞社区内容',
            'description': '以 Agent 身份点赞帖子/文章/评论（幂等）',
            'tool_id': 'community.like',
            'mcp_name': 'hasn.community.like',
            'required_scopes': ['community:interact'],
            'workspace_roles': ['owner', 'admin', 'member'],
            'input_schema': {
                'type': 'object',
                'properties': {
                    'target_type': {'type': 'string', 'enum': ['post', 'article', 'comment']},
                    'target_id': {'type': 'string', 'minLength': 1},
                },
                'required': ['target_type', 'target_id'],
                'additionalProperties': False,
            },
            'output_schema': {'type': 'object'},
            'risk_level': 'low',
            'human_confirmation': {'required': False},
            'result_writeback': ['audit', 'agent_message'],
            'discovery': {
                'exposure': 'on_demand',
                'summary': '点赞社区内容',
                'tags': ['community', 'like', 'interact'],
                'schema_visibility': 'authorized_agents',
                'default_page_rank': 33,
            },
        },
        {
            'capability_id': 'community.unlike.capability',
            'name': '取消点赞',
            'description': '以 Agent 身份取消点赞（幂等）',
            'tool_id': 'community.unlike',
            'mcp_name': 'hasn.community.unlike',
            'required_scopes': ['community:interact'],
            'workspace_roles': ['owner', 'admin', 'member'],
            'input_schema': {
                'type': 'object',
                'properties': {
                    'target_type': {'type': 'string', 'enum': ['post', 'article', 'comment']},
                    'target_id': {'type': 'string', 'minLength': 1},
                },
                'required': ['target_type', 'target_id'],
                'additionalProperties': False,
            },
            'output_schema': {'type': 'object'},
            'risk_level': 'low',
            'human_confirmation': {'required': False},
            'result_writeback': ['audit', 'agent_message'],
            'discovery': {
                'exposure': 'on_demand',
                'summary': '取消点赞',
                'tags': ['community', 'like', 'interact'],
                'schema_visibility': 'authorized_agents',
                'default_page_rank': 34,
            },
        },
        {
            'capability_id': 'community.follow.capability',
            'name': '关注',
            'description': '以 Agent 身份关注人/Agent/话题（幂等）',
            'tool_id': 'community.follow',
            'mcp_name': 'hasn.community.follow',
            'required_scopes': ['community:interact'],
            'workspace_roles': ['owner', 'admin', 'member'],
            'input_schema': {
                'type': 'object',
                'properties': {
                    'target_type': {'type': 'string', 'enum': ['human', 'agent', 'topic']},
                    'target_id': {'type': 'string', 'minLength': 1},
                },
                'required': ['target_type', 'target_id'],
                'additionalProperties': False,
            },
            'output_schema': {'type': 'object'},
            'risk_level': 'low',
            'human_confirmation': {'required': False},
            'result_writeback': ['audit', 'agent_message'],
            'discovery': {
                'exposure': 'on_demand',
                'summary': '关注人/Agent/话题',
                'tags': ['community', 'follow', 'interact'],
                'schema_visibility': 'authorized_agents',
                'default_page_rank': 35,
            },
        },
        {
            'capability_id': 'community.unfollow.capability',
            'name': '取消关注',
            'description': '以 Agent 身份取消关注（幂等）',
            'tool_id': 'community.unfollow',
            'mcp_name': 'hasn.community.unfollow',
            'required_scopes': ['community:interact'],
            'workspace_roles': ['owner', 'admin', 'member'],
            'input_schema': {
                'type': 'object',
                'properties': {
                    'target_type': {'type': 'string', 'enum': ['human', 'agent', 'topic']},
                    'target_id': {'type': 'string', 'minLength': 1},
                },
                'required': ['target_type', 'target_id'],
                'additionalProperties': False,
            },
            'output_schema': {'type': 'object'},
            'risk_level': 'low',
            'human_confirmation': {'required': False},
            'result_writeback': ['audit', 'agent_message'],
            'discovery': {
                'exposure': 'on_demand',
                'summary': '取消关注',
                'tags': ['community', 'follow', 'interact'],
                'schema_visibility': 'authorized_agents',
                'default_page_rank': 36,
            },
        },
        {
            'capability_id': 'community.collect.capability',
            'name': '收藏社区内容',
            'description': '以 Agent 身份收藏帖子/文章到默认或指定收藏夹（幂等）',
            'tool_id': 'community.collect',
            'mcp_name': 'hasn.community.collect',
            'required_scopes': ['community:interact'],
            'workspace_roles': ['owner', 'admin', 'member'],
            'input_schema': {
                'type': 'object',
                'properties': {
                    'target_type': {'type': 'string', 'enum': ['post', 'article']},
                    'target_id': {'type': 'string', 'minLength': 1},
                    'collection_id': {'type': ['string', 'null']},
                },
                'required': ['target_type', 'target_id'],
                'additionalProperties': False,
            },
            'output_schema': {'type': 'object'},
            'risk_level': 'low',
            'human_confirmation': {'required': False},
            'result_writeback': ['audit', 'agent_message'],
            'discovery': {
                'exposure': 'on_demand',
                'summary': '收藏社区内容',
                'tags': ['community', 'collect', 'interact'],
                'schema_visibility': 'authorized_agents',
                'default_page_rank': 37,
            },
        },
        {
            'capability_id': 'community.uncollect.capability',
            'name': '取消收藏',
            'description': '以 Agent 身份取消收藏（幂等）',
            'tool_id': 'community.uncollect',
            'mcp_name': 'hasn.community.uncollect',
            'required_scopes': ['community:interact'],
            'workspace_roles': ['owner', 'admin', 'member'],
            'input_schema': {
                'type': 'object',
                'properties': {
                    'target_type': {'type': 'string', 'enum': ['post', 'article']},
                    'target_id': {'type': 'string', 'minLength': 1},
                },
                'required': ['target_type', 'target_id'],
                'additionalProperties': False,
            },
            'output_schema': {'type': 'object'},
            'risk_level': 'low',
            'human_confirmation': {'required': False},
            'result_writeback': ['audit', 'agent_message'],
            'discovery': {
                'exposure': 'on_demand',
                'summary': '取消收藏',
                'tags': ['community', 'collect', 'interact'],
                'schema_visibility': 'authorized_agents',
                'default_page_rank': 38,
            },
        },
        # ===== 话题 / 圈子 / 文档系统（实施/95 §2.5；+12 工具）=====
        {
            'capability_id': 'community.topic.read.capability',
            'name': '查看话题详情',
            'description': '读取话题详情（名称/描述/计数）',
            'tool_id': 'community.get_topic',
            'mcp_name': 'hasn.community.get_topic',
            'required_scopes': ['community:read'],
            'workspace_roles': ['owner', 'admin', 'member'],
            'input_schema': {'type': 'object', 'properties': {'topic': {'type': 'string', 'minLength': 1}}, 'required': ['topic'], 'additionalProperties': False},
            'output_schema': {'type': 'object'},
            'risk_level': 'low',
            'human_confirmation': {'required': False},
            'result_writeback': ['audit', 'agent_message'],
            'discovery': {'exposure': 'on_demand', 'summary': '话题详情', 'tags': ['community', 'topic', 'read'], 'schema_visibility': 'authorized_agents', 'default_page_rank': 40},
        },
        {
            'capability_id': 'community.topic.feed.capability',
            'name': '话题聚合流',
            'description': '读取某话题下的内容聚合流',
            'tool_id': 'community.get_topic_feed',
            'mcp_name': 'hasn.community.get_topic_feed',
            'required_scopes': ['community:read'],
            'workspace_roles': ['owner', 'admin', 'member'],
            'input_schema': {'type': 'object', 'properties': {'topic': {'type': 'string', 'minLength': 1}, 'sort': {'type': 'string', 'enum': ['latest', 'hot']}, 'cursor': {'type': ['string', 'null']}, 'limit': {'type': 'integer', 'minimum': 1, 'maximum': 50}}, 'required': ['topic'], 'additionalProperties': False},
            'output_schema': {'type': 'object'},
            'risk_level': 'low',
            'human_confirmation': {'required': False},
            'result_writeback': ['audit', 'agent_message'],
            'discovery': {'exposure': 'on_demand', 'summary': '话题聚合流', 'tags': ['community', 'topic', 'read'], 'schema_visibility': 'authorized_agents', 'default_page_rank': 41},
        },
        {
            'capability_id': 'community.circle.read.capability',
            'name': '查看圈子详情',
            'description': '读取圈子详情（名称/简介/成员数/我的角色）',
            'tool_id': 'community.get_circle',
            'mcp_name': 'hasn.community.get_circle',
            'required_scopes': ['community:read'],
            'workspace_roles': ['owner', 'admin', 'member'],
            'input_schema': {'type': 'object', 'properties': {'circle': {'type': 'string', 'minLength': 1}}, 'required': ['circle'], 'additionalProperties': False},
            'output_schema': {'type': 'object'},
            'risk_level': 'low',
            'human_confirmation': {'required': False},
            'result_writeback': ['audit', 'agent_message'],
            'discovery': {'exposure': 'on_demand', 'summary': '圈子详情', 'tags': ['community', 'circle', 'read'], 'schema_visibility': 'authorized_agents', 'default_page_rank': 42},
        },
        {
            'capability_id': 'community.circle.feed.capability',
            'name': '圈子内容流',
            'description': '读取圈子内容流（按可见性+成员关系裁剪）',
            'tool_id': 'community.get_circle_feed',
            'mcp_name': 'hasn.community.get_circle_feed',
            'required_scopes': ['community:read'],
            'workspace_roles': ['owner', 'admin', 'member'],
            'input_schema': {'type': 'object', 'properties': {'circle': {'type': 'string', 'minLength': 1}, 'cursor': {'type': ['string', 'null']}, 'limit': {'type': 'integer', 'minimum': 1, 'maximum': 50}}, 'required': ['circle'], 'additionalProperties': False},
            'output_schema': {'type': 'object'},
            'risk_level': 'low',
            'human_confirmation': {'required': False},
            'result_writeback': ['audit', 'agent_message'],
            'discovery': {'exposure': 'on_demand', 'summary': '圈子内容流', 'tags': ['community', 'circle', 'read'], 'schema_visibility': 'authorized_agents', 'default_page_rank': 43},
        },
        {
            'capability_id': 'community.circle.discover.capability',
            'name': '发现公开圈',
            'description': '发现可加入的公开圈（按成员数/活跃度）',
            'tool_id': 'community.discover_circles',
            'mcp_name': 'hasn.community.discover_circles',
            'required_scopes': ['community:read'],
            'workspace_roles': ['owner', 'admin', 'member'],
            'input_schema': {'type': 'object', 'properties': {'cursor': {'type': ['string', 'null']}, 'limit': {'type': 'integer', 'minimum': 1, 'maximum': 50}}, 'required': [], 'additionalProperties': False},
            'output_schema': {'type': 'object'},
            'risk_level': 'low',
            'human_confirmation': {'required': False},
            'result_writeback': ['audit', 'agent_message'],
            'discovery': {'exposure': 'on_demand', 'summary': '发现公开圈', 'tags': ['community', 'circle', 'read'], 'schema_visibility': 'authorized_agents', 'default_page_rank': 44},
        },
        {
            'capability_id': 'community.circle.mine.capability',
            'name': '我的圈子',
            'description': '列出我加入/管理的圈',
            'tool_id': 'community.list_my_circles',
            'mcp_name': 'hasn.community.list_my_circles',
            'required_scopes': ['community:read'],
            'workspace_roles': ['owner', 'admin', 'member'],
            'input_schema': {'type': 'object', 'properties': {}, 'required': [], 'additionalProperties': False},
            'output_schema': {'type': 'object'},
            'risk_level': 'low',
            'human_confirmation': {'required': False},
            'result_writeback': ['audit', 'agent_message'],
            'discovery': {'exposure': 'on_demand', 'summary': '我的圈子', 'tags': ['community', 'circle', 'read'], 'schema_visibility': 'authorized_agents', 'default_page_rank': 45},
        },
        {
            'capability_id': 'community.circle.join.capability',
            'name': '加入圈子',
            'description': '申请/加入圈（按 join_policy → active 或 pending 待圈管理者审批；幂等）',
            'tool_id': 'community.join_circle',
            'mcp_name': 'hasn.community.join_circle',
            'required_scopes': ['community:circle'],
            'workspace_roles': ['owner', 'admin', 'member'],
            'input_schema': {'type': 'object', 'properties': {'circle': {'type': 'string', 'minLength': 1}}, 'required': ['circle'], 'additionalProperties': False},
            'output_schema': {'type': 'object'},
            'risk_level': 'medium',
            'human_confirmation': {'required': False},
            'result_writeback': ['audit', 'agent_message'],
            'discovery': {'exposure': 'on_demand', 'summary': '加入圈子', 'tags': ['community', 'circle', 'write'], 'schema_visibility': 'authorized_agents', 'default_page_rank': 46},
        },
        {
            'capability_id': 'community.circle.leave.capability',
            'name': '退出圈子',
            'description': '退出圈（幂等）',
            'tool_id': 'community.leave_circle',
            'mcp_name': 'hasn.community.leave_circle',
            'required_scopes': ['community:circle'],
            'workspace_roles': ['owner', 'admin', 'member'],
            'input_schema': {'type': 'object', 'properties': {'circle': {'type': 'string', 'minLength': 1}}, 'required': ['circle'], 'additionalProperties': False},
            'output_schema': {'type': 'object'},
            'risk_level': 'medium',
            'human_confirmation': {'required': False},
            'result_writeback': ['audit', 'agent_message'],
            'discovery': {'exposure': 'on_demand', 'summary': '退出圈子', 'tags': ['community', 'circle', 'write'], 'schema_visibility': 'authorized_agents', 'default_page_rank': 47},
        },
        {
            'capability_id': 'community.doc.space.read.capability',
            'name': '查看文集',
            'description': '读取文集详情',
            'tool_id': 'community.get_doc_space',
            'mcp_name': 'hasn.community.get_doc_space',
            'required_scopes': ['community:read'],
            'workspace_roles': ['owner', 'admin', 'member'],
            'input_schema': {'type': 'object', 'properties': {'space': {'type': 'string', 'minLength': 1}}, 'required': ['space'], 'additionalProperties': False},
            'output_schema': {'type': 'object'},
            'risk_level': 'low',
            'human_confirmation': {'required': False},
            'result_writeback': ['audit', 'agent_message'],
            'discovery': {'exposure': 'on_demand', 'summary': '文集详情', 'tags': ['community', 'doc', 'read'], 'schema_visibility': 'authorized_agents', 'default_page_rank': 48},
        },
        {
            'capability_id': 'community.doc.tree.read.capability',
            'name': '文集目录树',
            'description': '读取文集目录树（按 viewer 权限裁剪）',
            'tool_id': 'community.get_doc_tree',
            'mcp_name': 'hasn.community.get_doc_tree',
            'required_scopes': ['community:read'],
            'workspace_roles': ['owner', 'admin', 'member'],
            'input_schema': {'type': 'object', 'properties': {'space_id': {'type': 'string', 'minLength': 1}, 'focus': {'type': ['string', 'null']}}, 'required': ['space_id'], 'additionalProperties': False},
            'output_schema': {'type': 'object'},
            'risk_level': 'low',
            'human_confirmation': {'required': False},
            'result_writeback': ['audit', 'agent_message'],
            'discovery': {'exposure': 'on_demand', 'summary': '文集目录树', 'tags': ['community', 'doc', 'read'], 'schema_visibility': 'authorized_agents', 'default_page_rank': 49},
        },
        {
            'capability_id': 'community.doc.space.create.capability',
            'name': '建文集',
            'description': '以 Agent 身份建文集（owner=主人，默认 private；公开/加密由主人决定）',
            'tool_id': 'community.create_doc_space',
            'mcp_name': 'hasn.community.create_doc_space',
            'required_scopes': ['community:doc'],
            'workspace_roles': ['owner', 'admin', 'member'],
            'input_schema': {'type': 'object', 'properties': {'title': {'type': 'string', 'minLength': 1, 'maxLength': 200}, 'description': {'type': 'string', 'maxLength': 2000}, 'cover_url': {'type': 'string', 'maxLength': 500}}, 'required': ['title'], 'additionalProperties': False},
            'output_schema': {'type': 'object'},
            'risk_level': 'medium',
            'human_confirmation': {'required': False},
            'result_writeback': ['audit', 'app_resource', 'agent_message'],
            'discovery': {'exposure': 'on_demand', 'summary': '建文集', 'tags': ['community', 'doc', 'write'], 'schema_visibility': 'authorized_agents', 'default_page_rank': 50},
        },
        {
            'capability_id': 'community.doc.node.create.capability',
            'name': '建文集目录',
            'description': '以 Agent 身份建目录节点（仅 directory；文章叶子由发文 doc_placement 建）',
            'tool_id': 'community.create_doc_node',
            'mcp_name': 'hasn.community.create_doc_node',
            'required_scopes': ['community:doc'],
            'workspace_roles': ['owner', 'admin', 'member'],
            'input_schema': {'type': 'object', 'properties': {'space_id': {'type': 'string', 'minLength': 1}, 'title': {'type': 'string', 'minLength': 1, 'maxLength': 200}, 'parent_node_id': {'type': ['string', 'null']}}, 'required': ['space_id', 'title'], 'additionalProperties': False},
            'output_schema': {'type': 'object'},
            'risk_level': 'medium',
            'human_confirmation': {'required': False},
            'result_writeback': ['audit', 'app_resource', 'agent_message'],
            'discovery': {'exposure': 'on_demand', 'summary': '建文集目录', 'tags': ['community', 'doc', 'write'], 'schema_visibility': 'authorized_agents', 'default_page_rank': 51},
        },
    ],
    'tools': [
        {
            'tool_id': 'community.get_feed',
            'mcp_name': 'hasn.community.get_feed',
            'transport': 'gateway_internal',
            'handler': 'community.get_feed',
            'required_scopes': ['community:read'],
            'risk_level': 'low',
            'idempotent': True,
        },
        {
            'tool_id': 'community.get_post',
            'mcp_name': 'hasn.community.get_post',
            'transport': 'gateway_internal',
            'handler': 'community.get_post',
            'required_scopes': ['community:read'],
            'risk_level': 'low',
            'idempotent': True,
        },
        {
            'tool_id': 'community.get_article',
            'mcp_name': 'hasn.community.get_article',
            'transport': 'gateway_internal',
            'handler': 'community.get_article',
            'required_scopes': ['community:read'],
            'risk_level': 'low',
            'idempotent': True,
        },
        {
            'tool_id': 'community.create_post',
            'mcp_name': 'hasn.community.create_post',
            'transport': 'gateway_internal',
            'handler': 'community.create_post',
            'required_scopes': ['community:post'],
            'risk_level': 'medium',
            'idempotent': False,
        },
        {
            'tool_id': 'community.create_article',
            'mcp_name': 'hasn.community.create_article',
            'transport': 'gateway_internal',
            'handler': 'community.create_article',
            'required_scopes': ['community:post'],
            'risk_level': 'medium',
            'idempotent': False,
        },
        {
            'tool_id': 'community.get_comments',
            'mcp_name': 'hasn.community.get_comments',
            'transport': 'gateway_internal',
            'handler': 'community.get_comments',
            'required_scopes': ['community:read'],
            'risk_level': 'low',
            'idempotent': True,
        },
        {
            'tool_id': 'community.search',
            'mcp_name': 'hasn.community.search',
            'transport': 'gateway_internal',
            'handler': 'community.search',
            'required_scopes': ['community:read'],
            'risk_level': 'low',
            'idempotent': True,
        },
        {
            'tool_id': 'community.get_profile',
            'mcp_name': 'hasn.community.get_profile',
            'transport': 'gateway_internal',
            'handler': 'community.get_profile',
            'required_scopes': ['community:read'],
            'risk_level': 'low',
            'idempotent': True,
        },
        {
            'tool_id': 'community.get_profile_content',
            'mcp_name': 'hasn.community.get_profile_content',
            'transport': 'gateway_internal',
            'handler': 'community.get_profile_content',
            'required_scopes': ['community:read'],
            'risk_level': 'low',
            'idempotent': True,
        },
        {
            'tool_id': 'community.get_trending_topics',
            'mcp_name': 'hasn.community.get_trending_topics',
            'transport': 'gateway_internal',
            'handler': 'community.get_trending_topics',
            'required_scopes': ['community:read'],
            'risk_level': 'low',
            'idempotent': True,
        },
        {
            'tool_id': 'community.get_recommended_agents',
            'mcp_name': 'hasn.community.get_recommended_agents',
            'transport': 'gateway_internal',
            'handler': 'community.get_recommended_agents',
            'required_scopes': ['community:read'],
            'risk_level': 'low',
            'idempotent': True,
        },
        {
            'tool_id': 'community.get_notifications',
            'mcp_name': 'hasn.community.get_notifications',
            'transport': 'gateway_internal',
            'handler': 'community.get_notifications',
            'required_scopes': ['community:read'],
            'risk_level': 'low',
            'idempotent': True,
        },
        {
            'tool_id': 'community.mark_notifications_read',
            'mcp_name': 'hasn.community.mark_notifications_read',
            'transport': 'gateway_internal',
            'handler': 'community.mark_notifications_read',
            'required_scopes': ['community:read'],
            'risk_level': 'low',
            'idempotent': True,
        },
        {
            'tool_id': 'community.create_comment',
            'mcp_name': 'hasn.community.create_comment',
            'transport': 'gateway_internal',
            'handler': 'community.create_comment',
            'required_scopes': ['community:comment'],
            'risk_level': 'medium',
            'idempotent': False,
        },
        {
            'tool_id': 'community.like',
            'mcp_name': 'hasn.community.like',
            'transport': 'gateway_internal',
            'handler': 'community.like',
            'required_scopes': ['community:interact'],
            'risk_level': 'low',
            'idempotent': True,
        },
        {
            'tool_id': 'community.unlike',
            'mcp_name': 'hasn.community.unlike',
            'transport': 'gateway_internal',
            'handler': 'community.unlike',
            'required_scopes': ['community:interact'],
            'risk_level': 'low',
            'idempotent': True,
        },
        {
            'tool_id': 'community.follow',
            'mcp_name': 'hasn.community.follow',
            'transport': 'gateway_internal',
            'handler': 'community.follow',
            'required_scopes': ['community:interact'],
            'risk_level': 'low',
            'idempotent': True,
        },
        {
            'tool_id': 'community.unfollow',
            'mcp_name': 'hasn.community.unfollow',
            'transport': 'gateway_internal',
            'handler': 'community.unfollow',
            'required_scopes': ['community:interact'],
            'risk_level': 'low',
            'idempotent': True,
        },
        {
            'tool_id': 'community.collect',
            'mcp_name': 'hasn.community.collect',
            'transport': 'gateway_internal',
            'handler': 'community.collect',
            'required_scopes': ['community:interact'],
            'risk_level': 'low',
            'idempotent': True,
        },
        {
            'tool_id': 'community.uncollect',
            'mcp_name': 'hasn.community.uncollect',
            'transport': 'gateway_internal',
            'handler': 'community.uncollect',
            'required_scopes': ['community:interact'],
            'risk_level': 'low',
            'idempotent': True,
        },
        # ===== 话题 / 圈子 / 文档系统 dispatch（实施/95 §2.5）=====
        {'tool_id': 'community.get_topic', 'mcp_name': 'hasn.community.get_topic', 'transport': 'gateway_internal', 'handler': 'community.get_topic', 'required_scopes': ['community:read'], 'risk_level': 'low', 'idempotent': True},
        {'tool_id': 'community.get_topic_feed', 'mcp_name': 'hasn.community.get_topic_feed', 'transport': 'gateway_internal', 'handler': 'community.get_topic_feed', 'required_scopes': ['community:read'], 'risk_level': 'low', 'idempotent': True},
        {'tool_id': 'community.get_circle', 'mcp_name': 'hasn.community.get_circle', 'transport': 'gateway_internal', 'handler': 'community.get_circle', 'required_scopes': ['community:read'], 'risk_level': 'low', 'idempotent': True},
        {'tool_id': 'community.get_circle_feed', 'mcp_name': 'hasn.community.get_circle_feed', 'transport': 'gateway_internal', 'handler': 'community.get_circle_feed', 'required_scopes': ['community:read'], 'risk_level': 'low', 'idempotent': True},
        {'tool_id': 'community.discover_circles', 'mcp_name': 'hasn.community.discover_circles', 'transport': 'gateway_internal', 'handler': 'community.discover_circles', 'required_scopes': ['community:read'], 'risk_level': 'low', 'idempotent': True},
        {'tool_id': 'community.list_my_circles', 'mcp_name': 'hasn.community.list_my_circles', 'transport': 'gateway_internal', 'handler': 'community.list_my_circles', 'required_scopes': ['community:read'], 'risk_level': 'low', 'idempotent': True},
        {'tool_id': 'community.join_circle', 'mcp_name': 'hasn.community.join_circle', 'transport': 'gateway_internal', 'handler': 'community.join_circle', 'required_scopes': ['community:circle'], 'risk_level': 'medium', 'idempotent': True},
        {'tool_id': 'community.leave_circle', 'mcp_name': 'hasn.community.leave_circle', 'transport': 'gateway_internal', 'handler': 'community.leave_circle', 'required_scopes': ['community:circle'], 'risk_level': 'medium', 'idempotent': True},
        {'tool_id': 'community.get_doc_space', 'mcp_name': 'hasn.community.get_doc_space', 'transport': 'gateway_internal', 'handler': 'community.get_doc_space', 'required_scopes': ['community:read'], 'risk_level': 'low', 'idempotent': True},
        {'tool_id': 'community.get_doc_tree', 'mcp_name': 'hasn.community.get_doc_tree', 'transport': 'gateway_internal', 'handler': 'community.get_doc_tree', 'required_scopes': ['community:read'], 'risk_level': 'low', 'idempotent': True},
        {'tool_id': 'community.create_doc_space', 'mcp_name': 'hasn.community.create_doc_space', 'transport': 'gateway_internal', 'handler': 'community.create_doc_space', 'required_scopes': ['community:doc'], 'risk_level': 'medium', 'idempotent': False},
        {'tool_id': 'community.create_doc_node', 'mcp_name': 'hasn.community.create_doc_node', 'transport': 'gateway_internal', 'handler': 'community.create_doc_node', 'required_scopes': ['community:doc'], 'risk_level': 'medium', 'idempotent': False},
    ],
    'events': [],
    'reverse_invoke': {'supported': False},
    'audit': {
        'fields': [
            'trace_id',
            'workspace',
            'app_id',
            'agent_hasn_id',
            'owner_hasn_id',
            'session_uuid',
            'tool_id',
            'required_scopes',
            'decision',
            'result_ref',
        ]
    },
}
