from pathlib import Path
from typing import Any

class XdbSearcher:
    def __init__(self, *, contentBuff: Any) -> None: ...
    @staticmethod
    def loadContentFromFile(*, dbfile: str | Path) -> Any: ...
    def search(self, ip: str) -> str: ...
