from pathlib import Path

class XdbSearcher:
    def __init__(self, dbfile: str | Path | None = ..., vectorIndex: object | None = ..., contentBuff: bytes | None = ...) -> None: ...
    @staticmethod
    def loadContentFromFile(dbfile: str | Path) -> bytes: ...
    def search(self, ip: str) -> str: ...
