from collections.abc import Callable
from typing import Any

class AsyncRedisManager:
    def __init__(self, url: str, **kwargs: Any) -> None: ...

class AsyncServer:
    def __init__(self, **kwargs: Any) -> None: ...
    def event(self, handler: Callable[..., Any]) -> Callable[..., Any]: ...
    def on(self, event: str) -> Callable[[Callable[..., Any]], Callable[..., Any]]: ...
    async def emit(self, event: str, data: Any = ..., to: str | None = ..., **kwargs: Any) -> None: ...

class ASGIApp:
    def __init__(
        self,
        socketio_server: AsyncServer,
        other_asgi_app: Any = ...,
        socketio_path: str = ...,
        **kwargs: Any,
    ) -> None: ...
    async def __call__(self, scope: Any, receive: Any, send: Any) -> None: ...
