class ParsedUserAgent:
    def get_os(self) -> str | None: ...
    def get_browser(self) -> str | None: ...
    def get_device(self) -> str | None: ...

def parse(user_agent_string: str) -> ParsedUserAgent: ...
